# Generated by Django 5.1.2 on 2024-10-14 08:08

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customuser_otp_alter_otp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=app.models.get_default_expires_at),
        ),
    ]
